### PR TITLE
Tacotron2 v2

### PR DESCRIPTION
**Pull request by zyb8543d**
Update

### CODE REVIEW

**Comment by ilhamprayudha** [comment]
@begeekmyfriend hello can I ask ? how to order samples generated wavenet can 1 minute ?

**Comment by begeekmyfriend** [comment]
@ilhamprayudha Please refer to the README of r9y9's [wavenet vocoder](https://github.com/r9y9/wavenet_vocoder).

**Comment by begeekmyfriend** [comment]
Too many conflicts. Closing...

**Comment by ilhamprayudha** [comment]
@begeekmyfriend this is the result of wavenet training , how to get more results from 0,5 
step-160000-waveplot
d

**Comment by begeekmyfriend** [comment]
@ilhamprayudha Your result is very good, how many steps did you trained?

**Comment by ilhamprayudha** [comment]
@begeekmyfriend  2000 for tacotron training & 350000 for wavenet training

**Comment by begeekmyfriend** [comment]
@ilhamprayudha What is your dataset? For Chinese mandarin or English?

**Comment by ilhamprayudha** [comment]
@begeekmyfriend i use indonesia dataset, can you tell me how to generate sample if all the step is clear in tacotron-2 rayhane mamah?

**Comment by begeekmyfriend** [comment]
@ilhamprayudha I did not try Rayhane's wavenet but r9y9's one. I think you need to find the location of the  `checkpoint_path` of wavenet and then try typing
> python synthesize.py --model='WaveNet'

I think you need to read the README of r9y9's README first.

**Comment by ilhamprayudha** [comment]
`python3 synthesize.py --model='WaveNet' --name=WaveNet --output_dir=waveljnew  `
i try this code to synthesize checkpoint wavenet .   and this is result 
[result.zip](https://github.com/begeekmyfriend/Tacotron-2/files/2221849/result.zip)

**Comment by begeekmyfriend** [comment]
@ilhamprayudha That is strange I have succeeded to synthesize the audio out by r9y9's wavenet vocoder. Did you find the location of the checkpoint model of wavenet? Try to load it by adding `--checkpoint` option.

**Comment by ilhamprayudha** [comment]
@begeekmyfriend  i already try using `--checkpoint`.   
how to use r9y9 using the results of rayhane's tacotron ?
can the r9y9 input use mel spec from rayhane results?


this the log from my syntesize using rayhane, 
is there something wrong ?


Using TensorFlow backend.
loaded model at logs-WaveNet/wave_pretrained/wavenet_model.ckpt-360000

**Comment by begeekmyfriend** [comment]
[Here](https://github.com/r9y9/Tacotron-2/tree/wavenet-integration) is r9y9's tacotron porting. You can see the `wavenet-integration` branch for this purpose. And [here](https://colab.research.google.com/github/r9y9/Colaboratory/blob/master/Tacotron2_and_WaveNet_text_to_speech_demo.ipynb) is the online note written by r9y9 for how to integrate tacotron and wavenet vocoder. Good luck.

**Comment by ilhamprayudha** [comment]
see from r9y9 tacotron porting and online note, is not it the same as rayhane's branch whether there is anything different from both ?

**Comment by begeekmyfriend** [comment]
Sorry, I did not look closely into it...

**Comment by ilhamprayudha** [comment]
@begeekmyfriend 
i try [this](https://github.com/r9y9/wavenet_vocoder) 
train and syntesize using ./data/  from preprocessing rayhane
use this `python train.py --data-root=./data/ --speaker-id=0 \
    --hparams="cin_channels=80,gin_channels=-1` ,
what am I doing right ?


because I do not feel like using a Tacotron train just wavenet.

**Comment by ilhamprayudha** [comment]
i try r9y9 wavenet vocoder, its syntentys one sentence in +-20 minutes ?

**Pull request closed without merging**
